### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by VictimHan** [r-cui/PostprandialHyperHypoPrediction#1]

**Comment by VictimHan** [comment]
May I ask if you can provide the ohiot1dm dataset? I am a student and cannot apply. My email is 827714185@qq.com

**Comment by r-cui** [comment]
Hi,

I'm afraid that we cannot share the data due to our agreement with the data provider.
The only way to access the dataset is via an official request to the provider, which is available at http://smarthealth.cs.ohio.edu/OhioT1DM-dataset.html

Best,
Ran

**Comment by VictimHan** [comment]
okay thanks
&nbsp;


Han
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ran ***@***.***&gt;; 
发送时间: 2023年5月19日(星期五) 晚上8:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [r-cui/PostprandialHyperHypoPrediction] dataset (Issue #1)





 
Hi,
 
i'm afraid that we cannot share the data due to our agreement with the data provider.
 The only way to access the dataset is via an official request to the provider, which is available at http://smarthealth.cs.ohio.edu/OhioT1DM-dataset.html
 
Best,
 Ran
